### ISSUE TITLE
feat: 로그인 기능 구현

### ISSUE THREAD

**Issue by swywssaid** [TodaysFail/TodaysFail-FE#2]
## ⭐ 주요 기능 
로그인 기능을 구현합니다

### 닉네임 유효성 검사 (중복 검사 포함)
- [x] 특수 문자 입력 시, 특수 문자가 입력 안 됨
- [x] 닉네임 글자 수를 초과했을 때, 일정 글자 수 이상 텍스트 입력 안 됨, 글자 수 표시(10자 제한)
- [x] 중복 되었을 때, '이미 존재하는 닉네임입니다' 경고문 아래 발생
- [x] 중복 안 되었을 때, '사용 가능한 닉네임입니다 : )' 아래 표시
- [x] 중복 검사 미실시 혹은 실패 시, 시작하기 버튼 비활성화
- [x] 닉네임을 입력하지 않으면, 시작하기 버튼 비활성화
- [x] 유효성 검사 통과 시, 시작하기 버튼 활성화

### 닉네임 등록
- [x] 닉네임 인풋 영역을 클릭했을 때, 닉네임 입력 영역에 포커싱
- [x] 닉네임 등록 성공 시, 마이페이지로 리다이렉트
- [x] 닉네임 등록 성공 시, 로컬 스토리지에 닉네임 저장
- [x] 닉네임 등록 성공 시, 서버에 닉네임 전달

### 로그인 페이지에 접속 시
- [x] 로컬 스토리지에 닉네임 있는 상태로 접속 시, 마이페이지로 리다이렉트

## 📄 참고 사항
- 스타일을 제외한 기능 구현 완료

**Comment by kdomo** [comment]
@swywssaid 닉네임 10자 입니닷!
